Metrics/LineLength:
  Max: 175

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 42

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false
